//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingATournament_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class torneo
    {
        public int Id { get; set; }
        public string Disciplina { get; set; }
        public Nullable<int> NumeroEquipos { get; set; }
        public Nullable<double> CostoInscripcion { get; set; }
        public Nullable<int> NumeroRondas { get; set; }
        public Nullable<int> DispoinibilidadLugares { get; set; }
    }
}
